# Generated by Django 5.0.6 on 2024-07-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='Data_submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
